"""add target weekly gain to user

Revision ID: 171a9ba4af96
Revises: 23b4f603688a
Create Date: 2026-01-03 23:27:42.259671

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "171a9ba4af96"
down_revision: str | Sequence[str] | None = "23b4f603688a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("target_weekly_gain", sa.Float(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "target_weekly_gain")
    # ### end Alembic commands ###
