"""initial

Revision ID: 43c72f647236
Revises:
Create Date: 2025-09-04 00:03:36.806547

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43c72f647236"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "fridges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fridges_id"), "fridges", ["id"], unique=False)
    op.create_table(
        "weights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="weight_user_date_uc"),
    )
    op.create_index(op.f("ix_weights_id"), "weights", ["id"], unique=False)
    op.create_table(
        "fridge_meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fridge_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fridge_id"],
            ["fridges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fridge_meals_id"), "fridge_meals", ["id"], unique=False)
    op.create_table(
        "fridge_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fridge_id", sa.Integer(), nullable=True),
        sa.Column("product_name", sa.String(), nullable=True),
        sa.Column("calories_100g", sa.Float(), nullable=True),
        sa.Column("proteins_100g", sa.Float(), nullable=True),
        sa.Column("fats_100g", sa.Float(), nullable=True),
        sa.Column("carbs_100g", sa.Float(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "FRUIT",
                "VEGETABLE",
                "GRAINS",
                "DAIRY",
                "MEAT_FISH",
                "PLANT_PROTEIN",
                "FATS",
                "DRINKS",
                "SNACKS",
                name="food_category",
            ),
            nullable=True,
        ),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fridge_id"],
            ["fridges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fridge_products_id"), "fridge_products", ["id"], unique=False
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("weight_id", sa.Integer(), nullable=True),
        sa.Column("neck", sa.Float(), nullable=True),
        sa.Column("biceps", sa.Float(), nullable=True),
        sa.Column("chest", sa.Float(), nullable=True),
        sa.Column("waist", sa.Float(), nullable=True),
        sa.Column("hips", sa.Float(), nullable=True),
        sa.Column("thighs", sa.Float(), nullable=True),
        sa.Column("calves", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["weight_id"],
            ["weights.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "date", name="measurement_user_date_uc"),
    )
    op.create_index(op.f("ix_measurements_id"), "measurements", ["id"], unique=False)
    op.create_table(
        "fridge_meal_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("fridge_meal_id", sa.Integer(), nullable=True),
        sa.Column("fridge_product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fridge_meal_id"],
            ["fridge_meals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fridge_product_id"],
            ["fridge_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_fridge_meal_ingredients_id"),
        "fridge_meal_ingredients",
        ["id"],
        unique=False,
    )
    op.create_table(
        "meals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("fridge_meal_id", sa.Integer(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "BREAKFAST", "LUNCH", "DINNER", "SNACK", "SUPPER", name="meal_type"
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fridge_meal_id"],
            ["fridge_meals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meals_id"), "meals", ["id"], unique=False)
    op.create_table(
        "meal_ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("meal_id", sa.Integer(), nullable=True),
        sa.Column("fridge_product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fridge_product_id"],
            ["fridge_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_meal_ingredients_id"), "meal_ingredients", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meal_ingredients_id"), table_name="meal_ingredients")
    op.drop_table("meal_ingredients")
    op.drop_index(op.f("ix_meals_id"), table_name="meals")
    op.drop_table("meals")
    op.drop_index(
        op.f("ix_fridge_meal_ingredients_id"), table_name="fridge_meal_ingredients"
    )
    op.drop_table("fridge_meal_ingredients")
    op.drop_index(op.f("ix_measurements_id"), table_name="measurements")
    op.drop_table("measurements")
    op.drop_index(op.f("ix_fridge_products_id"), table_name="fridge_products")
    op.drop_table("fridge_products")
    op.drop_index(op.f("ix_fridge_meals_id"), table_name="fridge_meals")
    op.drop_table("fridge_meals")
    op.drop_index(op.f("ix_weights_id"), table_name="weights")
    op.drop_table("weights")
    op.drop_index(op.f("ix_fridges_id"), table_name="fridges")
    op.drop_table("fridges")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
