"""Refactor meals to flat MealLog

Revision ID: 54905e0df487
Revises: 4ec84316bf18
Create Date: 2025-12-31 00:45:51.179980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54905e0df487"
down_revision: str | Sequence[str] | None = "4ec84316bf18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meal_ingredients_id"), table_name="meal_ingredients")
    op.drop_index(
        op.f("ix_meal_ingredients_details_product_name"),
        table_name="meal_ingredients_details",
    )
    op.drop_table("meal_ingredients_details")
    op.drop_index(op.f("ix_meal_ingredients_meal_id"), table_name="meal_ingredients")
    op.drop_table("meal_ingredients")
    op.add_column("meals", sa.Column("weight", sa.Float(), nullable=False))
    op.add_column("meals", sa.Column("name", sa.String(), nullable=False))
    op.add_column("meals", sa.Column("calories", sa.Float(), nullable=False))
    op.add_column("meals", sa.Column("proteins", sa.Float(), nullable=False))
    op.add_column("meals", sa.Column("fats", sa.Float(), nullable=False))
    op.add_column("meals", sa.Column("carbs", sa.Float(), nullable=False))
    op.drop_constraint(op.f("uq_user_meal_per_day_type"), "meals", type_="unique")
    op.create_index(op.f("ix_meals_name"), "meals", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meals_name"), table_name="meals")
    op.create_unique_constraint(
        op.f("uq_user_meal_per_day_type"),
        "meals",
        ["user_id", "date", "type"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("meals", "carbs")
    op.drop_column("meals", "fats")
    op.drop_column("meals", "proteins")
    op.drop_column("meals", "calories")
    op.drop_column("meals", "name")
    op.drop_column("meals", "weight")
    op.create_table(
        "meal_ingredients_details",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "calories_100g",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "proteins_100g",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fats_100g",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "carbs_100g",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["meal_ingredients.id"],
            name=op.f("meal_ingredients_details_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meal_ingredients_details_pkey")),
    )
    op.create_index(
        op.f("ix_meal_ingredients_details_product_name"),
        "meal_ingredients_details",
        ["product_name"],
        unique=False,
    )
    op.create_table(
        "meal_ingredients",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("meal_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meals.id"],
            name=op.f("meal_ingredients_meal_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("meal_ingredients_pkey")),
    )
    op.create_index(
        op.f("ix_meal_ingredients_meal_id"),
        "meal_ingredients",
        ["meal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_meal_ingredients_id"), "meal_ingredients", ["id"], unique=False
    )
    # ### end Alembic commands ###
