"""refactor_meals_add_ingredient_details

Revision ID: 8f270fdfe0cf
Revises: 43c72f647236
Create Date: 2025-09-23 14:09:03.691269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f270fdfe0cf'
down_revision: Union[str, Sequence[str], None] = '43c72f647236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_ingredients_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('calories_100g', sa.Float(), nullable=False),
    sa.Column('proteins_100g', sa.Float(), nullable=False),
    sa.Column('fats_100g', sa.Float(), nullable=False),
    sa.Column('carbs_100g', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['meal_ingredients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_ingredients_details_product_name'), 'meal_ingredients_details', ['product_name'], unique=False)
    op.alter_column('fridge_meal_ingredients', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fridge_meal_ingredients', 'fridge_meal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fridge_meal_ingredients', 'fridge_product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fridge_meal_ingredients_fridge_meal_id'), 'fridge_meal_ingredients', ['fridge_meal_id'], unique=False)
    op.drop_constraint(op.f('fridge_meal_ingredients_fridge_meal_id_fkey'), 'fridge_meal_ingredients', type_='foreignkey')
    op.drop_constraint(op.f('fridge_meal_ingredients_fridge_product_id_fkey'), 'fridge_meal_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'fridge_meal_ingredients', 'fridge_meals', ['fridge_meal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fridge_meal_ingredients', 'fridge_products', ['fridge_product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fridge_meals', 'fridge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fridge_meals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_fridge_meals_fridge_id'), 'fridge_meals', ['fridge_id'], unique=False)
    op.create_index(op.f('ix_fridge_meals_is_favourite'), 'fridge_meals', ['is_favourite'], unique=False)
    op.create_index(op.f('ix_fridge_meals_name'), 'fridge_meals', ['name'], unique=False)
    op.create_unique_constraint('un_fridge_meal_name', 'fridge_meals', ['fridge_id', 'name'])
    op.drop_constraint(op.f('fridge_meals_fridge_id_fkey'), 'fridge_meals', type_='foreignkey')
    op.create_foreign_key(None, 'fridge_meals', 'fridges', ['fridge_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fridge_products', 'fridge_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('fridge_products', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('fridge_products', 'calories_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fridge_products', 'proteins_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fridge_products', 'fats_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('fridge_products', 'carbs_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_fridge_products_fridge_id'), 'fridge_products', ['fridge_id'], unique=False)
    op.create_index(op.f('ix_fridge_products_is_favourite'), 'fridge_products', ['is_favourite'], unique=False)
    op.create_index(op.f('ix_fridge_products_product_name'), 'fridge_products', ['product_name'], unique=False)
    op.create_unique_constraint('un_fridge_product_name', 'fridge_products', ['fridge_id', 'product_name'])
    op.drop_constraint(op.f('fridge_products_fridge_id_fkey'), 'fridge_products', type_='foreignkey')
    op.create_foreign_key(None, 'fridge_products', 'fridges', ['fridge_id'], ['id'], ondelete='CASCADE')
    op.alter_column('fridges', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_fridges_user_id'), 'fridges', ['user_id'], unique=False)
    op.drop_constraint(op.f('fridges_user_id_fkey'), 'fridges', type_='foreignkey')
    op.create_foreign_key(None, 'fridges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('meal_ingredients', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('meal_ingredients', 'meal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_meal_ingredients_meal_id'), 'meal_ingredients', ['meal_id'], unique=False)
    op.drop_constraint(op.f('meal_ingredients_meal_id_fkey'), 'meal_ingredients', type_='foreignkey')
    op.drop_constraint(op.f('meal_ingredients_fridge_product_id_fkey'), 'meal_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'meal_ingredients', 'meals', ['meal_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meal_ingredients', 'fridge_product_id')
    op.alter_column('meals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('meals', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.create_index(op.f('ix_meals_date'), 'meals', ['date'], unique=False)
    op.create_index(op.f('ix_meals_type'), 'meals', ['type'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.drop_constraint(op.f('meals_fridge_meal_id_fkey'), 'meals', type_='foreignkey')
    op.drop_constraint(op.f('meals_user_id_fkey'), 'meals', type_='foreignkey')
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('meals', 'fridge_meal_id')
    op.alter_column('measurements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('measurements', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.create_index(op.f('ix_measurements_date'), 'measurements', ['date'], unique=False)
    op.create_index(op.f('ix_measurements_user_id'), 'measurements', ['user_id'], unique=False)
    op.drop_constraint(op.f('measurements_user_id_fkey'), 'measurements', type_='foreignkey')
    op.drop_constraint(op.f('measurements_weight_id_fkey'), 'measurements', type_='foreignkey')
    op.create_foreign_key(None, 'measurements', 'weights', ['weight_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'measurements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.alter_column('weights', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('weights', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('weights', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.create_index(op.f('ix_weights_date'), 'weights', ['date'], unique=False)
    op.create_index(op.f('ix_weights_user_id'), 'weights', ['user_id'], unique=False)
    op.drop_constraint(op.f('weights_user_id_fkey'), 'weights', type_='foreignkey')
    op.create_foreign_key(None, 'weights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weights', type_='foreignkey')
    op.create_foreign_key(op.f('weights_user_id_fkey'), 'weights', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_weights_user_id'), table_name='weights')
    op.drop_index(op.f('ix_weights_date'), table_name='weights')
    op.alter_column('weights', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('weights', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('weights', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.drop_constraint(None, 'measurements', type_='foreignkey')
    op.create_foreign_key(op.f('measurements_weight_id_fkey'), 'measurements', 'weights', ['weight_id'], ['id'])
    op.create_foreign_key(op.f('measurements_user_id_fkey'), 'measurements', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_measurements_user_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_date'), table_name='measurements')
    op.alter_column('measurements', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('measurements', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('meals', sa.Column('fridge_meal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.create_foreign_key(op.f('meals_user_id_fkey'), 'meals', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('meals_fridge_meal_id_fkey'), 'meals', 'fridge_meals', ['fridge_meal_id'], ['id'])
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_type'), table_name='meals')
    op.drop_index(op.f('ix_meals_date'), table_name='meals')
    op.alter_column('meals', 'date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('meals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('meal_ingredients', sa.Column('fridge_product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'meal_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('meal_ingredients_fridge_product_id_fkey'), 'meal_ingredients', 'fridge_products', ['fridge_product_id'], ['id'])
    op.create_foreign_key(op.f('meal_ingredients_meal_id_fkey'), 'meal_ingredients', 'meals', ['meal_id'], ['id'])
    op.drop_index(op.f('ix_meal_ingredients_meal_id'), table_name='meal_ingredients')
    op.alter_column('meal_ingredients', 'meal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('meal_ingredients', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint(None, 'fridges', type_='foreignkey')
    op.create_foreign_key(op.f('fridges_user_id_fkey'), 'fridges', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_fridges_user_id'), table_name='fridges')
    op.alter_column('fridges', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'fridge_products', type_='foreignkey')
    op.create_foreign_key(op.f('fridge_products_fridge_id_fkey'), 'fridge_products', 'fridges', ['fridge_id'], ['id'])
    op.drop_constraint('un_fridge_product_name', 'fridge_products', type_='unique')
    op.drop_index(op.f('ix_fridge_products_product_name'), table_name='fridge_products')
    op.drop_index(op.f('ix_fridge_products_is_favourite'), table_name='fridge_products')
    op.drop_index(op.f('ix_fridge_products_fridge_id'), table_name='fridge_products')
    op.alter_column('fridge_products', 'carbs_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fridge_products', 'fats_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fridge_products', 'proteins_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fridge_products', 'calories_100g',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('fridge_products', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fridge_products', 'fridge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'fridge_meals', type_='foreignkey')
    op.create_foreign_key(op.f('fridge_meals_fridge_id_fkey'), 'fridge_meals', 'fridges', ['fridge_id'], ['id'])
    op.drop_constraint('un_fridge_meal_name', 'fridge_meals', type_='unique')
    op.drop_index(op.f('ix_fridge_meals_name'), table_name='fridge_meals')
    op.drop_index(op.f('ix_fridge_meals_is_favourite'), table_name='fridge_meals')
    op.drop_index(op.f('ix_fridge_meals_fridge_id'), table_name='fridge_meals')
    op.alter_column('fridge_meals', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('fridge_meals', 'fridge_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'fridge_meal_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'fridge_meal_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('fridge_meal_ingredients_fridge_product_id_fkey'), 'fridge_meal_ingredients', 'fridge_products', ['fridge_product_id'], ['id'])
    op.create_foreign_key(op.f('fridge_meal_ingredients_fridge_meal_id_fkey'), 'fridge_meal_ingredients', 'fridge_meals', ['fridge_meal_id'], ['id'])
    op.drop_index(op.f('ix_fridge_meal_ingredients_fridge_meal_id'), table_name='fridge_meal_ingredients')
    op.alter_column('fridge_meal_ingredients', 'fridge_product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fridge_meal_ingredients', 'fridge_meal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fridge_meal_ingredients', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_meal_ingredients_details_product_name'), table_name='meal_ingredients_details')
    op.drop_table('meal_ingredients_details')
    # ### end Alembic commands ###
