"""Add profile and system fields to users

Revision ID: 9997d78d485f
Revises: 8f270fdfe0cf
Create Date: 2025-10-19 01:58:12.237625

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9997d78d485f"
down_revision: str | Sequence[str] | None = "8f270fdfe0cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    gender_enum = sa.Enum("MALE", "FEMALE", name="gender")
    gender_enum.create(op.get_bind(), checkfirst=True)

    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("gender", gender_enum, nullable=True))
    op.add_column("users", sa.Column("activity_level", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "activity_level")
    op.drop_column("users", "gender")
    op.drop_column("users", "age")
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "is_active")

    gender_enum = sa.Enum("MALE", "FEMALE", name="gender")
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
